/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripsRoute,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TripsRoute,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => TripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRouteWithChildren
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/signup': typeof SignupRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRouteWithChildren
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/budget'
    | '/discover'
    | '/login'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/settings'
    | '/shared'
    | '/signup'
    | '/trips'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/budget'
    | '/discover'
    | '/login'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/settings'
    | '/shared'
    | '/signup'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/budget'
    | '/discover'
    | '/login'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/settings'
    | '/shared'
    | '/signup'
    | '/trips'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BudgetRoute: typeof BudgetRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PackingRoute: typeof PackingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  SignupRoute: typeof SignupRoute
  TripsRoute: typeof TripsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof TripsRoute
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof TripsRoute
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof TripsRoute
    }
  }
}

interface TripsRouteChildren {
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsNewRoute: typeof TripsNewRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsTripIdRoute: TripsTripIdRoute,
  TripsNewRoute: TripsNewRoute,
  TripsIndexRoute: TripsIndexRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  BudgetRoute: BudgetRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PackingRoute: PackingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  SignupRoute: SignupRoute,
  TripsRoute: TripsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
